### ISSUE TITLE
It fails read GoogleNews-vectors-negative300.bin distributed by Google

### ISSUE THREAD

**Issue by koreyou** [koreyou/word_embedding_loader#1]
Trying to load word2vec file Google raises following error.

```
Traceback (most recent call last):
  File "/home/koreyou/.pyenv/versions/root/bin/word-embedding-loader", line 11, in <module>
    load_entry_point('WordEmbeddingLoader', 'console_scripts', 'word-embedding-loader')()
  File "/home/koreyou/.pyenv/versions/2.7.12/envs/root/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/koreyou/.pyenv/versions/2.7.12/envs/root/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/koreyou/.pyenv/versions/2.7.12/envs/root/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/koreyou/.pyenv/versions/2.7.12/envs/root/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/koreyou/.pyenv/versions/2.7.12/envs/root/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/koreyou/work/word_embedding_loader/word_embedding_loader/cli.py", line 45, in convert
    binary=_input_choices[from_format][2])
  File "/home/koreyou/work/word_embedding_loader/word_embedding_loader/word_embedding.py", line 198, in load
    unicode_errors=unicode_errors, encoding=encoding)
  File "word_embedding_loader/loader/word2vec_bin.pyx", line 128, in word_embedding_loader.loader.word2vec_bin.load (word_embedding_loader/loader/word2vec_bin.cpp:3446)
    unicode_errors)
  File "word_embedding_loader/loader/word2vec_bin.pyx", line 101, in word_embedding_loader.loader.word2vec_bin._load_impl (word_embedding_loader/loader/word2vec_bin.cpp:2956)
    vocabs[ustring] = i
  File "/home/koreyou/.pyenv/versions/2.7.12/envs/root/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode bytes in position 0-1: unexpected end of data
```

**Comment by koreyou** [comment]
This is because GoogleNews-vectors-negative300.bin is encoded as latin-1, not unicode.

Current workaround is to specify `encoding='latin-1'`
